export const SET_TRAFFIC_LIGHT_VISIBILITY = 'race/SET_TRAFFIC_LIGHT_VISIBILITY';
export const SET_TRAFFIC_LIGHT_COLOR = 'race/SET_TRAFFIC_LIGHT_COLOR';
export const SET_START_TIME = 'race/SET_START_TIME';
export const SET_FINISH_TIME = 'race/SET_FINISH_TIME';
export const SET_RESULTS_DATA = 'race/SET_RESULTS_DATA';
export const SET_IS_RESULTS_READY = 'race/SET_IS_RESULTS_LOADING';
