export const SET_TRAFFIC_LIGHT_VISIBILITY = 'race/SET_TRAFFIC_LIGHT_VISIBILITY';
export const SET_TRAFFIC_LIGHT_COLOR = 'race/SET_TRAFFIC_LIGHT_COLOR';
export const SET_START_TIME = 'race/SET_START_TIME';
export const SET_FINISH_TIME = 'race/SET_FINISH_TIME';
export const SET_CURRENT_RACE_CARD = 'race/SET_SHOW_CURRENT_RACE_CARD';
